name: C/C++ CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: clean
        run: make clean
      - name: make
        run: make all
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        id: create_release
        with:
          # Artifact name
          name: ReleaseBinaries
          path: release/*
      - name: Upload the binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: release/*
